-- AlterTable
ALTER TABLE "Contact" ADD COLUMN     "date_created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ALTER TABLE "pages" 
-- ADD COLUMN "is_active" BOOLEAN DEFAULT FALSE,
-- ADD COLUMN "is_draft" BOOLEAN DEFAULT TRUE,
-- ADD COLUMN "page_body" TEXT;
